name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install .NET Framework Core
        run: Install-WindowsFeature Net-Framework-Core
      - name: Install .NET Framework Features
        run: Install-WindowsFeature Net-Framework-Features

      - name: Build
        run: msbuild "Rawr.sln" /p:Configuration=Release -m

      - name: Create Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Rawr
          path: bin\Release

      - name: Download the Build Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: Rawr
          path: bin\Release
